"""otif contratual por cliente (anamnese)

Revision ID: 3461cd4fe1c4
Revises: ddcecb970011
Create Date: 2026-07-31 17:13:28.138730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3461cd4fe1c4'
down_revision: Union[str, Sequence[str], None] = 'ddcecb970011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizacao', sa.Column('otif_contratual', sa.Numeric(precision=4, scale=2), nullable=True), schema='operacao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizacao', 'otif_contratual', schema='operacao')
    # ### end Alembic commands ###
