"""nivel de servico do pedido (exclusivo)

Revision ID: 371f55c49cb6
Revises: 3461cd4fe1c4
Create Date: 2026-07-31 17:24:53.321307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371f55c49cb6'
down_revision: Union[str, Sequence[str], None] = '3461cd4fe1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('nivel_servico', sa.String(length=10), server_default='PADRAO', nullable=False), schema='operacao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedido', 'nivel_servico', schema='operacao')
    # ### end Alembic commands ###
