"""cria schema operacao e grupo cadastro

Revision ID: 37a20a3ed169
Revises: 
Create Date: 2026-07-29 18:38:56.774123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a20a3ed169'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ajuste manual: autogenerate nao cria o schema em si
    op.execute("CREATE SCHEMA IF NOT EXISTS operacao")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizacao',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('sigla', sa.String(length=10), nullable=False),
    sa.Column('razao_social', sa.String(length=150), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('tipo_parceria', sa.String(length=10), nullable=False),
    sa.Column('porte', sa.String(length=10), nullable=True),
    sa.Column('segmento', sa.String(length=40), nullable=True),
    sa.Column('fl_entrega_agendada', sa.Boolean(), nullable=True),
    sa.Column('dt_inicio_contrato', sa.Date(), nullable=False),
    sa.Column('dt_cancelamento', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.CheckConstraint("porte IS NULL OR porte IN ('MICRO', 'PEQUENA', 'MEDIA', 'GRANDE', 'MEGA')", name=op.f('ck_organizacao_porte_valido')),
    sa.CheckConstraint("tipo_parceria IN ('CLIENTE', 'BASE', 'MATRIZ')", name=op.f('ck_organizacao_tipo_parceria_valido')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizacao')),
    sa.UniqueConstraint('cnpj', name=op.f('uq_organizacao_cnpj')),
    sa.UniqueConstraint('sigla', name=op.f('uq_organizacao_sigla')),
    schema='operacao'
    )
    op.create_table('rota',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rota')),
    sa.UniqueConstraint('codigo', name=op.f('uq_rota_codigo')),
    schema='operacao'
    )
    op.create_table('transportador',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('tipo', sa.String(length=15), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.CheckConstraint("tipo IN ('FROTA_PROPRIA', 'AGREGADO', 'CARRETEIRO', 'TRANSPORTADORA')", name=op.f('ck_transportador_tipo_valido')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transportador')),
    schema='operacao'
    )
    op.create_table('endereco',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('organizacao_id', sa.BigInteger(), nullable=False),
    sa.Column('nome_local', sa.String(length=150), nullable=False),
    sa.Column('documento', sa.String(length=14), nullable=True),
    sa.Column('logradouro', sa.String(length=200), nullable=False),
    sa.Column('bairro', sa.String(length=80), nullable=False),
    sa.Column('cidade', sa.String(length=80), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('fl_principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['operacao.organizacao.id'], name=op.f('fk_endereco_organizacao_id_organizacao'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_endereco')),
    schema='operacao'
    )
    op.create_table('item',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('grupo', sa.String(length=60), nullable=False),
    sa.Column('subgrupo', sa.String(length=60), nullable=False),
    sa.Column('peso_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('volume_m3', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['operacao.organizacao.id'], name=op.f('fk_item_cliente_id_organizacao'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item')),
    sa.UniqueConstraint('cliente_id', 'codigo', name=op.f('uq_item_cliente_id')),
    schema='operacao'
    )
    op.create_table('local_estoque',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('organizacao_id', sa.BigInteger(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['operacao.organizacao.id'], name=op.f('fk_local_estoque_organizacao_id_organizacao'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_local_estoque')),
    sa.UniqueConstraint('codigo', name=op.f('uq_local_estoque_codigo')),
    schema='operacao'
    )
    op.create_table('veiculo',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('transportador_id', sa.BigInteger(), nullable=False),
    sa.Column('placa', sa.String(length=8), nullable=False),
    sa.Column('tipo_veiculo', sa.String(length=30), nullable=False),
    sa.Column('capacidade_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['transportador_id'], ['operacao.transportador.id'], name=op.f('fk_veiculo_transportador_id_transportador'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_veiculo')),
    sa.UniqueConstraint('placa', name=op.f('uq_veiculo_placa')),
    schema='operacao'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veiculo', schema='operacao')
    op.drop_table('local_estoque', schema='operacao')
    op.drop_table('item', schema='operacao')
    op.drop_table('endereco', schema='operacao')
    op.drop_table('transportador', schema='operacao')
    op.drop_table('rota', schema='operacao')
    op.drop_table('organizacao', schema='operacao')
    # ### end Alembic commands ###
    # ajuste manual: desfaz tambem o schema (vazio neste ponto)
    op.execute("DROP SCHEMA IF EXISTS operacao")
