"""modal por minuta (pedido multimodal)

Revision ID: 5325249ec627
Revises: 371f55c49cb6
Create Date: 2026-07-31 17:30:58.308833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5325249ec627'
down_revision: Union[str, Sequence[str], None] = '371f55c49cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('minuta', sa.Column('modalidade_id', sa.BigInteger(), nullable=False), schema='operacao')
    op.create_foreign_key(op.f('fk_minuta_modalidade_id_modalidade'), 'minuta', 'modalidade', ['modalidade_id'], ['id'], source_schema='operacao', referent_schema='operacao', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_minuta_modalidade_id_modalidade'), 'minuta', schema='operacao', type_='foreignkey')
    op.drop_column('minuta', 'modalidade_id', schema='operacao')
    # ### end Alembic commands ###
