"""entrega em transito: fl_sucesso tri-estado

Revision ID: 7147ab7ed2f6
Revises: f3dac2eae39e
Create Date: 2026-08-04 17:10:42.887697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7147ab7ed2f6'
down_revision: Union[str, Sequence[str], None] = 'f3dac2eae39e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entrega', 'fl_sucesso',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='operacao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entrega', 'fl_sucesso',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='operacao')
    # ### end Alembic commands ###
