"""grupo configuracao + dominio de fases, modalidades e ocorrencias

Revision ID: be20d7763de7
Revises: 37a20a3ed169
Create Date: 2026-07-29 18:58:42.115906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be20d7763de7'
down_revision: Union[str, Sequence[str], None] = '37a20a3ed169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campanha',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.Column('dt_inicio', sa.Date(), nullable=False),
    sa.Column('dt_fim', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campanha')),
    schema='operacao'
    )
    op.create_table('fase',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('codigo', sa.String(length=2), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('fl_esporadica', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fase')),
    sa.UniqueConstraint('codigo', name=op.f('uq_fase_codigo')),
    sa.UniqueConstraint('ordem', name=op.f('uq_fase_ordem')),
    schema='operacao'
    )
    op.create_table('modalidade',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('nome', sa.String(length=15), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.CheckConstraint("nome IN ('RODOVIARIO', 'AEREO')", name=op.f('ck_modalidade_nome_valido')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modalidade')),
    sa.UniqueConstraint('nome', name=op.f('uq_modalidade_nome')),
    schema='operacao'
    )
    op.create_table('tipo_ocorrencia',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.Column('fl_impacta_prazo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tipo_ocorrencia')),
    sa.UniqueConstraint('codigo', name=op.f('uq_tipo_ocorrencia_codigo')),
    schema='operacao'
    )
    op.create_table('lead_time',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('modalidade_id', sa.BigInteger(), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('cidade', sa.String(length=80), nullable=False),
    sa.Column('dias_uteis', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modalidade_id'], ['operacao.modalidade.id'], name=op.f('fk_lead_time_modalidade_id_modalidade'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_time')),
    sa.UniqueConstraint('modalidade_id', 'uf', 'cidade', name=op.f('uq_lead_time_modalidade_id')),
    schema='operacao'
    )
    # ### end Alembic commands ###

    # ajuste manual: DADO DE DOMINIO nasce com o schema (vocabulario do processo).
    # LEAD_TIME e CAMPANHA ficam de fora: sao parametrizacao, populadas pelo gerador.
    fase = sa.table(
        'fase',
        sa.column('codigo', sa.String), sa.column('nome', sa.String),
        sa.column('ordem', sa.Integer), sa.column('fl_esporadica', sa.Boolean),
        schema='operacao',
    )
    op.bulk_insert(fase, [
        {'codigo': 'EA', 'nome': 'Em Aprovacao', 'ordem': 1, 'fl_esporadica': False},
        {'codigo': 'PC', 'nome': 'Pre-Conferencia', 'ordem': 2, 'fl_esporadica': False},
        {'codigo': 'DC', 'nome': 'Distribuicao de Cotas', 'ordem': 3, 'fl_esporadica': True},
        {'codigo': 'PL', 'nome': 'Planejamento', 'ordem': 4, 'fl_esporadica': False},
        {'codigo': 'EX', 'nome': 'Em Analise (urgencia extrema)', 'ordem': 5, 'fl_esporadica': True},
        {'codigo': 'CF', 'nome': 'Coleta Fisica', 'ordem': 6, 'fl_esporadica': False},
        {'codigo': 'ME', 'nome': 'Manuseio', 'ordem': 7, 'fl_esporadica': False},
        {'codigo': 'EN', 'nome': 'Emissao (NF-e)', 'ordem': 8, 'fl_esporadica': False},
        {'codigo': 'EC', 'nome': 'Expedicao', 'ordem': 9, 'fl_esporadica': False},
        {'codigo': 'CE', 'nome': 'Confirmacao de Entrega', 'ordem': 10, 'fl_esporadica': False},
    ])

    modalidade = sa.table(
        'modalidade',
        sa.column('nome', sa.String), sa.column('ativo', sa.Boolean),
        schema='operacao',
    )
    op.bulk_insert(modalidade, [
        {'nome': 'RODOVIARIO', 'ativo': True},
        {'nome': 'AEREO', 'ativo': True},
    ])

    tipo_ocorrencia = sa.table(
        'tipo_ocorrencia',
        sa.column('codigo', sa.String), sa.column('descricao', sa.String),
        sa.column('fl_impacta_prazo', sa.Boolean),
        schema='operacao',
    )
    op.bulk_insert(tipo_ocorrencia, [
        {'codigo': 'REENTREGA', 'descricao': 'Nova tentativa apos falha de entrega', 'fl_impacta_prazo': True},
        {'codigo': 'DEVOLUCAO', 'descricao': 'Material devolvido a origem', 'fl_impacta_prazo': True},
        {'codigo': 'AVARIA', 'descricao': 'Material danificado no transporte/manuseio', 'fl_impacta_prazo': True},
        {'codigo': 'DESTINATARIO_AUSENTE', 'descricao': 'Ninguem para receber no destino', 'fl_impacta_prazo': True},
        {'codigo': 'ENDERECO_NAO_LOCALIZADO', 'descricao': 'Endereco de entrega nao encontrado', 'fl_impacta_prazo': True},
        {'codigo': 'AGENDAMENTO', 'descricao': 'Entrega reagendada com o destinatario', 'fl_impacta_prazo': True},
        {'codigo': 'EXTRAVIO', 'descricao': 'Material extraviado na cadeia', 'fl_impacta_prazo': True},
        {'codigo': 'DIVERGENCIA_CADASTRO', 'descricao': 'Erro de item/endereco pego na pre-conferencia', 'fl_impacta_prazo': False},
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_time', schema='operacao')
    op.drop_table('tipo_ocorrencia', schema='operacao')
    op.drop_table('modalidade', schema='operacao')
    op.drop_table('fase', schema='operacao')
    op.drop_table('campanha', schema='operacao')
    # ### end Alembic commands ###
