"""sla_fase: regua interna de duracao por fase

Revision ID: ddcecb970011
Revises: eaf1f662b037
Create Date: 2026-07-30 21:23:50.330037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddcecb970011'
down_revision: Union[str, Sequence[str], None] = 'eaf1f662b037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sla_fase',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('fase_id', sa.BigInteger(), nullable=False),
    sa.Column('horas_uteis_meta', sa.Integer(), nullable=False),
    sa.Column('horas_uteis_limite', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fase_id'], ['operacao.fase.id'], name=op.f('fk_sla_fase_fase_id_fase'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sla_fase')),
    sa.UniqueConstraint('fase_id', name=op.f('uq_sla_fase_fase_id')),
    schema='operacao'
    )
    # ### end Alembic commands ###

    # ajuste manual: DADO DE DOMINIO — a régua calibrada com o Tiago (horas úteis;
    # CE fica fora: o prazo dela é o LEAD_TIME). Dias derivam na exibição (h/8).
    reguas = [
        ('EA', 8, 16), ('PC', 4, 8), ('DC', 4, 8), ('PL', 8, 16), ('EX', 2, 4),
        ('CF', 8, 16), ('ME', 8, 16), ('EN', 2, 4), ('EC', 8, 16),
    ]
    for codigo, meta, limite in reguas:
        op.execute(
            sa.text(
                'INSERT INTO operacao.sla_fase (fase_id, horas_uteis_meta, horas_uteis_limite) '
                'SELECT id, :m, :l FROM operacao.fase WHERE codigo = :c'
            ).bindparams(m=meta, l=limite, c=codigo)
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sla_fase', schema='operacao')
    # ### end Alembic commands ###
