"""schema custos (financeiro) + entrada na base

Revision ID: e1fee09a5b4e
Revises: fc25aab37f06
Create Date: 2026-07-29 19:40:55.830488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1fee09a5b4e'
down_revision: Union[str, Sequence[str], None] = 'fc25aab37f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ajuste manual: o sistema financeiro vive em schema proprio (sem FK p/ operacao)
    op.execute("CREATE SCHEMA IF NOT EXISTS custos")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_custo',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('nome', sa.String(length=15), nullable=False),
    sa.CheckConstraint("nome IN ('RODOVIARIO', 'AEREO', 'BASE', 'MONTADOR', 'INSUMOS', 'IMPOSTO_DIFAL', 'OUTROS')", name=op.f('ck_categoria_custo_nome_valido')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categoria_custo')),
    sa.UniqueConstraint('nome', name=op.f('uq_categoria_custo_nome')),
    schema='custos'
    )
    op.create_table('faturamento_operacao',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('cliente_sigla', sa.String(length=10), nullable=False),
    sa.Column('referencia_numero', sa.String(length=20), nullable=True),
    sa.Column('tipo_operacao', sa.String(length=12), nullable=False),
    sa.Column('competencia', sa.String(length=7), nullable=False),
    sa.Column('valor_com_icms', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_icms', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('dt_faturamento', sa.Date(), nullable=False),
    sa.CheckConstraint("tipo_operacao IN ('TRANSPORTE', 'ARMAZENAGEM', 'COLETA', 'POSITIVACAO')", name=op.f('ck_faturamento_operacao_tipo_operacao_valido')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faturamento_operacao')),
    schema='custos'
    )
    op.create_index(op.f('ix_custos_faturamento_operacao_cliente_sigla'), 'faturamento_operacao', ['cliente_sigla'], unique=False, schema='custos')
    op.create_index(op.f('ix_custos_faturamento_operacao_referencia_numero'), 'faturamento_operacao', ['referencia_numero'], unique=False, schema='custos')
    op.create_table('parametro_financeiro',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('chave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parametro_financeiro')),
    sa.UniqueConstraint('chave', name=op.f('uq_parametro_financeiro_chave')),
    schema='custos'
    )
    op.create_table('tarifa_armazenagem',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('cliente_sigla', sa.String(length=10), nullable=False),
    sa.Column('valor_m3', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('aliquota_ad_valorem', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('valor_minimo_mensal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tarifa_armazenagem')),
    sa.UniqueConstraint('cliente_sigla', name=op.f('uq_tarifa_armazenagem_cliente_sigla')),
    schema='custos'
    )
    op.create_table('custo_operacao',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('cliente_sigla', sa.String(length=10), nullable=False),
    sa.Column('referencia_numero', sa.String(length=20), nullable=True),
    sa.Column('categoria_custo_id', sa.BigInteger(), nullable=False),
    sa.Column('prestador_nome', sa.String(length=150), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('dt_competencia', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_custo_id'], ['custos.categoria_custo.id'], name=op.f('fk_custo_operacao_categoria_custo_id_categoria_custo'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custo_operacao')),
    schema='custos'
    )
    op.create_index(op.f('ix_custos_custo_operacao_cliente_sigla'), 'custo_operacao', ['cliente_sigla'], unique=False, schema='custos')
    op.create_index(op.f('ix_custos_custo_operacao_referencia_numero'), 'custo_operacao', ['referencia_numero'], unique=False, schema='custos')
    op.add_column('entrega', sa.Column('dt_entrada_base', sa.DateTime(), nullable=True), schema='operacao')
    # ### end Alembic commands ###

    # ajuste manual: DADO DE DOMINIO do financeiro
    categoria = sa.table('categoria_custo', sa.column('nome', sa.String), schema='custos')
    op.bulk_insert(categoria, [
        {'nome': 'RODOVIARIO'},
        {'nome': 'AEREO'},
        {'nome': 'BASE'},
        {'nome': 'MONTADOR'},
        {'nome': 'INSUMOS'},
        {'nome': 'IMPOSTO_DIFAL'},
        {'nome': 'OUTROS'},
    ])
    parametro = sa.table(
        'parametro_financeiro',
        sa.column('chave', sa.String), sa.column('valor', sa.Numeric),
        sa.column('descricao', sa.String),
        schema='custos',
    )
    op.bulk_insert(parametro, [
        {'chave': 'taxa_imposto_faturamento', 'valor': 0.0673,
         'descricao': 'Imposto sobre faturamento aplicado na MC (parametro de negocio)'},
        {'chave': 'fator_cubagem_rodoviario', 'valor': 300,
         'descricao': 'Kg por m3 para peso cubado no modal rodoviario'},
        {'chave': 'fator_cubagem_aereo', 'valor': 166.7,
         'descricao': 'Kg por m3 para peso cubado no modal aereo'},
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entrega', 'dt_entrada_base', schema='operacao')
    op.drop_index(op.f('ix_custos_custo_operacao_referencia_numero'), table_name='custo_operacao', schema='custos')
    op.drop_index(op.f('ix_custos_custo_operacao_cliente_sigla'), table_name='custo_operacao', schema='custos')
    op.drop_table('custo_operacao', schema='custos')
    op.drop_table('tarifa_armazenagem', schema='custos')
    op.drop_table('parametro_financeiro', schema='custos')
    op.drop_index(op.f('ix_custos_faturamento_operacao_referencia_numero'), table_name='faturamento_operacao', schema='custos')
    op.drop_index(op.f('ix_custos_faturamento_operacao_cliente_sigla'), table_name='faturamento_operacao', schema='custos')
    op.drop_table('faturamento_operacao', schema='custos')
    op.drop_table('categoria_custo', schema='custos')
    # ### end Alembic commands ###
    # ajuste manual: desfaz tambem o schema (vazio neste ponto)
    op.execute("DROP SCHEMA IF EXISTS custos")
