"""grupo movimento: o coracao da operacao

Revision ID: fc25aab37f06
Revises: 517a23a1474a
Create Date: 2026-07-29 19:25:39.958476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc25aab37f06'
down_revision: Union[str, Sequence[str], None] = '517a23a1474a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coleta',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=False),
    sa.Column('endereco_origem_id', sa.BigInteger(), nullable=False),
    sa.Column('local_estoque_destino_id', sa.BigInteger(), nullable=False),
    sa.Column('transportador_id', sa.BigInteger(), nullable=False),
    sa.Column('veiculo_id', sa.BigInteger(), nullable=True),
    sa.Column('dt_solicitacao', sa.DateTime(), nullable=False),
    sa.Column('dt_prevista', sa.Date(), nullable=False),
    sa.Column('dt_coleta', sa.DateTime(), nullable=True),
    sa.Column('peso_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('volume_m3', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('finalidade', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=11), nullable=False),
    sa.CheckConstraint("finalidade IN ('DESCARTE', 'RETORNO_ESTOQUE')", name=op.f('ck_coleta_finalidade_valida')),
    sa.CheckConstraint("status IN ('SOLICITADA', 'COLETADA', 'CANCELADA')", name=op.f('ck_coleta_status_valido')),
    sa.ForeignKeyConstraint(['cliente_id'], ['operacao.organizacao.id'], name=op.f('fk_coleta_cliente_id_organizacao'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['endereco_origem_id'], ['operacao.endereco.id'], name=op.f('fk_coleta_endereco_origem_id_endereco'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['local_estoque_destino_id'], ['operacao.local_estoque.id'], name=op.f('fk_coleta_local_estoque_destino_id_local_estoque'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transportador_id'], ['operacao.transportador.id'], name=op.f('fk_coleta_transportador_id_transportador'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['veiculo_id'], ['operacao.veiculo.id'], name=op.f('fk_coleta_veiculo_id_veiculo'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coleta')),
    sa.UniqueConstraint('numero', name=op.f('uq_coleta_numero')),
    schema='operacao'
    )
    op.create_table('estoque_snapshot',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('local_estoque_id', sa.BigInteger(), nullable=False),
    sa.Column('qtde_saldo', sa.Integer(), nullable=False),
    sa.Column('m3_ocupado', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('valor_material', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_danificado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['operacao.item.id'], name=op.f('fk_estoque_snapshot_item_id_item'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['local_estoque_id'], ['operacao.local_estoque.id'], name=op.f('fk_estoque_snapshot_local_estoque_id_local_estoque'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_estoque_snapshot')),
    sa.UniqueConstraint('data', 'item_id', 'local_estoque_id', name=op.f('uq_estoque_snapshot_data')),
    schema='operacao'
    )
    op.create_index(op.f('ix_operacao_estoque_snapshot_item_id'), 'estoque_snapshot', ['item_id'], unique=False, schema='operacao')
    op.create_table('minuta',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('transportador_id', sa.BigInteger(), nullable=False),
    sa.Column('veiculo_id', sa.BigInteger(), nullable=True),
    sa.Column('rota_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo_carga', sa.String(length=12), nullable=False),
    sa.Column('dt_expedicao', sa.DateTime(), nullable=False),
    sa.CheckConstraint("tipo_carga IN ('CONSOLIDADA', 'EXCLUSIVA')", name=op.f('ck_minuta_tipo_carga_valido')),
    sa.ForeignKeyConstraint(['rota_id'], ['operacao.rota.id'], name=op.f('fk_minuta_rota_id_rota'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transportador_id'], ['operacao.transportador.id'], name=op.f('fk_minuta_transportador_id_transportador'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['veiculo_id'], ['operacao.veiculo.id'], name=op.f('fk_minuta_veiculo_id_veiculo'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_minuta')),
    sa.UniqueConstraint('numero', name=op.f('uq_minuta_numero')),
    schema='operacao'
    )
    op.create_table('pedido',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=False),
    sa.Column('endereco_id', sa.BigInteger(), nullable=False),
    sa.Column('modalidade_id', sa.BigInteger(), nullable=False),
    sa.Column('campanha_id', sa.BigInteger(), nullable=True),
    sa.Column('canal', sa.String(length=5), nullable=False),
    sa.Column('tipo_atendimento', sa.String(length=20), nullable=True),
    sa.Column('dt_solicitacao', sa.DateTime(), nullable=False),
    sa.Column('dt_prazo_saida_expedicao', sa.Date(), nullable=False),
    sa.Column('dt_prazo_entrega', sa.Date(), nullable=False),
    sa.Column('peso_teorico_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('volume_teorico_m3', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('peso_real_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('volume_real_m3', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('nf_numero', sa.String(length=20), nullable=True),
    sa.CheckConstraint("canal IN ('GRADE', 'WEB')", name=op.f('ck_pedido_canal_valido')),
    sa.CheckConstraint("tipo_atendimento IS NULL OR tipo_atendimento IN ('ENTREGA_DIRETA', 'RETIRA_BASE', 'ENTREGA_VIA_BASE')", name=op.f('ck_pedido_tipo_atendimento_valido')),
    sa.ForeignKeyConstraint(['campanha_id'], ['operacao.campanha.id'], name=op.f('fk_pedido_campanha_id_campanha'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cliente_id'], ['operacao.organizacao.id'], name=op.f('fk_pedido_cliente_id_organizacao'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['endereco_id'], ['operacao.endereco.id'], name=op.f('fk_pedido_endereco_id_endereco'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modalidade_id'], ['operacao.modalidade.id'], name=op.f('fk_pedido_modalidade_id_modalidade'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pedido')),
    sa.UniqueConstraint('numero', name=op.f('uq_pedido_numero')),
    schema='operacao'
    )
    op.create_table('recebimento',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('local_estoque_id', sa.BigInteger(), nullable=False),
    sa.Column('numero_agendamento', sa.String(length=20), nullable=True),
    sa.Column('fornecedor_nome', sa.String(length=150), nullable=True),
    sa.Column('nf_entrada', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('dt_validade', sa.Date(), nullable=True),
    sa.Column('dt_prevista', sa.Date(), nullable=False),
    sa.Column('dt_recebimento', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.CheckConstraint("status IN ('AGUARDANDO', 'RECEBIDO', 'DIVERGENTE')", name=op.f('ck_recebimento_status_valido')),
    sa.ForeignKeyConstraint(['item_id'], ['operacao.item.id'], name=op.f('fk_recebimento_item_id_item'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['local_estoque_id'], ['operacao.local_estoque.id'], name=op.f('fk_recebimento_local_estoque_id_local_estoque'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recebimento')),
    schema='operacao'
    )
    op.create_index(op.f('ix_operacao_recebimento_item_id'), 'recebimento', ['item_id'], unique=False, schema='operacao')
    op.create_table('entrega',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('pedido_id', sa.BigInteger(), nullable=False),
    sa.Column('minuta_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo_perna', sa.String(length=20), nullable=False),
    sa.Column('endereco_destino_id', sa.BigInteger(), nullable=False),
    sa.Column('dt_prevista', sa.Date(), nullable=False),
    sa.Column('dt_chegada', sa.DateTime(), nullable=True),
    sa.Column('recebedor', sa.String(length=100), nullable=True),
    sa.Column('fl_sucesso', sa.Boolean(), nullable=False),
    sa.Column('fl_canhoto', sa.Boolean(), nullable=False),
    sa.CheckConstraint("tipo_perna IN ('DIRETA', 'TRANSFERENCIA_BASE', 'ULTIMA_MILHA_BASE')", name=op.f('ck_entrega_tipo_perna_valido')),
    sa.ForeignKeyConstraint(['endereco_destino_id'], ['operacao.endereco.id'], name=op.f('fk_entrega_endereco_destino_id_endereco'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['minuta_id'], ['operacao.minuta.id'], name=op.f('fk_entrega_minuta_id_minuta'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pedido_id'], ['operacao.pedido.id'], name=op.f('fk_entrega_pedido_id_pedido'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entrega')),
    schema='operacao'
    )
    op.create_index(op.f('ix_operacao_entrega_minuta_id'), 'entrega', ['minuta_id'], unique=False, schema='operacao')
    op.create_index(op.f('ix_operacao_entrega_pedido_id'), 'entrega', ['pedido_id'], unique=False, schema='operacao')
    op.create_table('ordem_coleta',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('pedido_id', sa.BigInteger(), nullable=False),
    sa.Column('local_estoque_id', sa.BigInteger(), nullable=False),
    sa.Column('dt_emissao', sa.DateTime(), nullable=False),
    sa.Column('dt_conclusao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.CheckConstraint("status IN ('EMITIDA', 'COLETADA', 'CANCELADA')", name=op.f('ck_ordem_coleta_status_valido')),
    sa.ForeignKeyConstraint(['local_estoque_id'], ['operacao.local_estoque.id'], name=op.f('fk_ordem_coleta_local_estoque_id_local_estoque'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pedido_id'], ['operacao.pedido.id'], name=op.f('fk_ordem_coleta_pedido_id_pedido'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ordem_coleta')),
    sa.UniqueConstraint('pedido_id', 'local_estoque_id', name=op.f('uq_ordem_coleta_pedido_id')),
    schema='operacao'
    )
    op.create_index(op.f('ix_operacao_ordem_coleta_pedido_id'), 'ordem_coleta', ['pedido_id'], unique=False, schema='operacao')
    op.create_table('pedido_fase',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('pedido_id', sa.BigInteger(), nullable=False),
    sa.Column('fase_id', sa.BigInteger(), nullable=False),
    sa.Column('dt_entrada', sa.DateTime(), nullable=False),
    sa.Column('dt_saida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fase_id'], ['operacao.fase.id'], name=op.f('fk_pedido_fase_fase_id_fase'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pedido_id'], ['operacao.pedido.id'], name=op.f('fk_pedido_fase_pedido_id_pedido'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pedido_fase')),
    sa.UniqueConstraint('pedido_id', 'fase_id', name=op.f('uq_pedido_fase_pedido_id')),
    schema='operacao'
    )
    op.create_index(op.f('ix_operacao_pedido_fase_pedido_id'), 'pedido_fase', ['pedido_id'], unique=False, schema='operacao')
    op.create_table('pedido_item',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('pedido_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['operacao.item.id'], name=op.f('fk_pedido_item_item_id_item'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pedido_id'], ['operacao.pedido.id'], name=op.f('fk_pedido_item_pedido_id_pedido'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pedido_item')),
    sa.UniqueConstraint('pedido_id', 'item_id', name=op.f('uq_pedido_item_pedido_id')),
    schema='operacao'
    )
    op.create_table('positivacao',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=False),
    sa.Column('pedido_id', sa.BigInteger(), nullable=True),
    sa.Column('endereco_id', sa.BigInteger(), nullable=False),
    sa.Column('campanha_id', sa.BigInteger(), nullable=True),
    sa.Column('parceiro_nome', sa.String(length=150), nullable=False),
    sa.Column('dt_abertura', sa.Date(), nullable=False),
    sa.Column('dt_servico', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.CheckConstraint("status IN ('ABERTA', 'REALIZADA', 'CANCELADA')", name=op.f('ck_positivacao_status_valido')),
    sa.ForeignKeyConstraint(['campanha_id'], ['operacao.campanha.id'], name=op.f('fk_positivacao_campanha_id_campanha'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cliente_id'], ['operacao.organizacao.id'], name=op.f('fk_positivacao_cliente_id_organizacao'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['endereco_id'], ['operacao.endereco.id'], name=op.f('fk_positivacao_endereco_id_endereco'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pedido_id'], ['operacao.pedido.id'], name=op.f('fk_positivacao_pedido_id_pedido'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positivacao')),
    sa.UniqueConstraint('numero', name=op.f('uq_positivacao_numero')),
    schema='operacao'
    )
    op.create_table('retirada_base',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('pedido_id', sa.BigInteger(), nullable=False),
    sa.Column('base_id', sa.BigInteger(), nullable=False),
    sa.Column('dt_retirada', sa.DateTime(), nullable=False),
    sa.Column('retirado_por', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['base_id'], ['operacao.organizacao.id'], name=op.f('fk_retirada_base_base_id_organizacao'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pedido_id'], ['operacao.pedido.id'], name=op.f('fk_retirada_base_pedido_id_pedido'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retirada_base')),
    sa.UniqueConstraint('pedido_id', name=op.f('uq_retirada_base_pedido_id')),
    schema='operacao'
    )
    op.create_table('ocorrencia',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('pedido_id', sa.BigInteger(), nullable=False),
    sa.Column('entrega_id', sa.BigInteger(), nullable=True),
    sa.Column('tipo_ocorrencia_id', sa.BigInteger(), nullable=False),
    sa.Column('dt_ocorrencia', sa.DateTime(), nullable=False),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('dt_cancelada', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entrega_id'], ['operacao.entrega.id'], name=op.f('fk_ocorrencia_entrega_id_entrega'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pedido_id'], ['operacao.pedido.id'], name=op.f('fk_ocorrencia_pedido_id_pedido'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipo_ocorrencia_id'], ['operacao.tipo_ocorrencia.id'], name=op.f('fk_ocorrencia_tipo_ocorrencia_id_tipo_ocorrencia'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ocorrencia')),
    schema='operacao'
    )
    op.create_index(op.f('ix_operacao_ocorrencia_pedido_id'), 'ocorrencia', ['pedido_id'], unique=False, schema='operacao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operacao_ocorrencia_pedido_id'), table_name='ocorrencia', schema='operacao')
    op.drop_table('ocorrencia', schema='operacao')
    op.drop_table('retirada_base', schema='operacao')
    op.drop_table('positivacao', schema='operacao')
    op.drop_table('pedido_item', schema='operacao')
    op.drop_index(op.f('ix_operacao_pedido_fase_pedido_id'), table_name='pedido_fase', schema='operacao')
    op.drop_table('pedido_fase', schema='operacao')
    op.drop_index(op.f('ix_operacao_ordem_coleta_pedido_id'), table_name='ordem_coleta', schema='operacao')
    op.drop_table('ordem_coleta', schema='operacao')
    op.drop_index(op.f('ix_operacao_entrega_pedido_id'), table_name='entrega', schema='operacao')
    op.drop_index(op.f('ix_operacao_entrega_minuta_id'), table_name='entrega', schema='operacao')
    op.drop_table('entrega', schema='operacao')
    op.drop_index(op.f('ix_operacao_recebimento_item_id'), table_name='recebimento', schema='operacao')
    op.drop_table('recebimento', schema='operacao')
    op.drop_table('pedido', schema='operacao')
    op.drop_table('minuta', schema='operacao')
    op.drop_index(op.f('ix_operacao_estoque_snapshot_item_id'), table_name='estoque_snapshot', schema='operacao')
    op.drop_table('estoque_snapshot', schema='operacao')
    op.drop_table('coleta', schema='operacao')
    # ### end Alembic commands ###
